repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.3.0
  hooks:
  - id: reorder-python-imports
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
  - id: end-of-file-fixer
  - id: check-json
  - id: check-yaml
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: requirements-txt-fixer
    files: .*requirements.*\.(txt|in)
- repo: https://gitlab.com/pycqa/flake8
  rev: "3.8.3"
  hooks:
  - id: flake8
